### ISSUE TITLE
Metal suggestions

### ISSUE THREAD

**Issue by 0Navis0** [MinecraftModDevelopmentMods/ModernMetals#76]
I had already suggested it on Curse, but I move it here for it becomes more visible. So here is all the metals which exist classified by their type. I don't request to add everything, but I hope it can help you guys to know where to go. ;)

- Alkali Metals (highly reactive with water and oxygen, rarely found natively for this reason)
    - ~~Lithium~~
    - Sodium
    - Potassium
    - Rubidium
    - Cesium
    - ~~Francium~~ (too unastable and radioactive for existing)

- Alkaline Earth Metals
    - ~~Berylium~~
    - ~~Magnesium~~
    - Calcium
    - Strontium
    - Baryum
    - Radium

- Lanthanides and Actinides
    - Scandium
    - Yttrium
    - Lanthanum
    - Cerium
    - Praseodymium
    - Neodymium
    - Promethium
    - Samarium
    - Europium
    - Gadolinium
    - Terbium
    - Dysprosium
    - Holmium
    - Erbium
    - Thulium
    - Ytterbium
    - Lutetium
    - Actinium
    - ~~Thorium~~
    - Protactinium
    - ~~Uranium~~
    - Neptunium
    - ~~Plutonium~~
    - Americium
    - Curium
    - Berkelium
    - Californium

- Transition Metals
    - ~~Titanium~~
    - Vanadium
    - ~~Chromium~~
    - ~~Mangagnese~~
    - ~~Iron~~
    - Cobalt
    - ~~Nickel~~
    - ~~Copper~~
    - ~~Zirconium~~
    - Niobium
    - Molybdenum
    - Technetium/Panormium
    - Ruthenium
    - Rhodium
    - Palladium
    - ~~Silver~~
    - Hafnium
    - ~~Tantalum~~
    - ~~Tungsten~~
    - Rhenium
    - ~~Osmium~~
    - ~~Iridium~~
    - ~~Platinum~~
    - ~~Gold~~

- Post Transition Metals
    - ~~Aluminium~~
    - ~~Zinc~~
    - Gallium
    - ~~Cadmium~~
    - Indium
    - ~~Tin~~
    - ~~Mercury~~
    - Thallium
    - ~~Lead~~
    - ~~Bismuth~~
    - Polonium

- Metalloids
    - ~~Boron~~
    - ~~Silicium~~
    - Germanium
    - Arsenic
    - ~~Antimony~~
    - Tellurium
    - ~~Astatine~~ (too unastable and radioactive for existing)

- Near Metalloids
    - ~~Carbon~~
    - ~~Phosphorus~~
    - Selenium
    - Iodine

- Non Metals
    - ~~Sulfur~~

**Comment by Hypsellis** [comment]
A little error I noticed, Lithium and Silicium (or Silicon, but Silicium the proper term) should be moved into metals module since they are metals. I suggest too to move the alloys to a separate module from the metals, and reunite the base and modern metals module. I think it would be more logic and easy for you guys to manage. 
Selenium should misses to minerals. For the halogens it's more complex since they can exist in gaseous and liquid state at temperate temperature (fluorine, chlorine, bromine), or even solid and liquid and gaseous state for the iodine.
